version: '3'

services:
  pgsql:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:latest
    environment:
      PGSSLMODE: disable
    tty: true
    entrypoint: sh
    volumes:
      - ./conf/db/migrations:/migrations
